categories/api/urls.py
from django.urls import path

from .views import CategoryApiView

app_name = "categories"
urlpatterns = [path("", CategoryApiView.as_view())]

categories/urls.py
from django.urls import include, path

from categories.api.urls import urlpatterns

from .views import (
    CategoryCreateView,
    CategoryDeleteVIew,
    CategoryDetailView,
    CategoryUpdateView,
    ParentCategoryListView,
)

app_name = 'category'
urlpatterns = [
    path("", ParentCategoryListView.as_view(), name="parent"),
    path("<int:pk>/", CategoryDetailView.as_view(), name="detail"),
    path("create/", CategoryCreateView.as_view(), name="create"),
    path("update/<int:pk>/", CategoryUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", CategoryDeleteVIew.as_view(), name="delete"),
    path("api/", include(urlpatterns)),
]

divar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("wantads.urls", namespace="want_ad")),
    path("category/", include("categories.urls")),
    path("panel/", include("config.urls", namespace="config")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += [
        path("silk/", include("silk.urls", namespace="silk")),
        path("__debug__/", include("debug_toolbar.urls")),
    ]

categories/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    name = models.CharField(
        max_length=125,
    )
    parent = TreeForeignKey(
        "self",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="children",
    )

    class MPTTMeta:
        order_insertion_by = ("name",)

    def __str__(self):
        return self.name

    @property
    def children_count(self):
        return self.get_descendant_count()

categories/forms.py
from django import forms

from .models import Category


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            "parent",
            "name",
        )
        labels = {"name": "نام دسته بندی", "parent": "دسته مادر"}

        widgets = {
            'parent': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.fields['parent'].empty_label = 'انتخاب کنید'

categories/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework import generics, response, status
from rest_framework.response import Response

from ..models import Category
from .serializers import CategorySerializer


class CategoryApiView(generics.GenericAPIView):
    serializer_class = CategorySerializer

    def get(self, request, *args, **kwargs):
        # try:
        # category_list = Category.objects.filter(parent=None)
        category_list = Category.objects.all()
        serializer = self.serializer_class(category_list, many=True)
        context = {
            "is_done": True,
            "message": "لیست دسته بندی ها",
            "data": serializer.data,
        }
        return Response(data=context)

    # except:
    #     context = {
    #         'is_done': False,
    #         'message': 'خطا دز انجام عملیات'
    #     }
    #     return Response(data=context)


#
# class CategoryWantApiView(generics.GenericAPIView):
#     serializer_class =
#
#     def get(self, request, *args, **kwargs):
#         try:
#             category_id = kwargs.get('id')
#             category_obj = get_object_or_404(Category, id=category_id)
#

categories/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from utils.mixins import AdminAccessMixin

from .forms import CategoryForm
from .models import Category


# Create your views here.


class ParentCategoryListView(AdminAccessMixin, ListView):
    queryset = Category.objects.filter(parent=None)
    template_name = "category/list.html"


class CategoryCreateView(AdminAccessMixin, SuccessMessageMixin, CreateView):
    model = Category
    form_class = CategoryForm
    template_name = "category/create.html"
    success_url = reverse_lazy('category:parent')
    success_message = "دسته یندی با موفقیت اضافه شذ"

    def form_invalid(self, form):
        messages.error(self.request, "", "danger")
        return super(CategoryCreateView, self).form_invalid(form)


class CategoryUpdateView(AdminAccessMixin, SuccessMessageMixin, UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = "category/update.html"
    success_url = reverse_lazy('category:parent')
    success_message = ""

    def form_invalid(self, form):
        messages.error(self.request, "", "danger")
        return super(CategoryUpdateView, self).form_invalid(form)


class CategoryDetailView(AdminAccessMixin, SuccessMessageMixin, DetailView):
    model = Category
    template_name = ""


class CategoryDeleteVIew(AdminAccessMixin, View):
    def get(self, request, *args, **kwargs):
        category_id = kwargs.get("pk")
        category_obj = get_object_or_404(Category, id=category_id)
        category_obj.delete()
        messages.success(request, "", "success")
        return redirect("")

categories/templates/category/create.html
{% extends 'base1.html' %}
<!-- end::header -->
{% block content %}
    <!-- begin::main-content -->
    <div class="main-content">

        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-success text-center">افزودن دسته بندی</h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">

                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <form method="post" action="">
                                        {% csrf_token %}
                                        {% for field in form.visible_fields %}
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">{{ field.label }}</label>
                                                {{ field }}
                                            </div>
                                        {% endfor %}
                                        <button type="submit" class="btn btn-primary">ثبت</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>

    </div>
    <!-- end::main-content -->
{% endblock content %}
<!-- begin::footer -->

categories/templates/category/list.html
{% extends "base1.html" %}
{% block content %}
    <main class="main-content">
        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-center">لیست دسته بندی ها</h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">


                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">دسته بندی ها</h6>
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">عنوان</th>
                                        <th scope="col">تعداد زیر دسته</th>
                                        <th scope="col">مشاهده زیر دسته ها</th>
                                        <th scope="col">ویرایش</th>
                                        <th scope="col">حذف</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for category in category_list %}
                                        <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>{{ category.name }}</td>
                                        <td>{{ category.children_count }}</td>
                                        <td><a class="btn  btn-info" href="">مشاهده</a></td>
                                        <td><a class="btn  btn-warning" href="{% url "category:update" category.pk %}">ویرایش</a></td>
                                        <td><a class="btn  btn-danger" href="{% url "category:delete" category.pk %}">حذف</a></td>
                                    {% empty %}
                                        <h1 class="text-center text-danger">تا کنون دسته بندی ثبت نشده</h1>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </main>
{% endblock content %}

categories/templates/category/update.html
{% extends 'base1.html' %}
<!-- end::header -->
{% block content %}
    <!-- begin::main-content -->
    <div class="main-content">

        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-warning text-center"> {{ object }}  ویرایش  دسته بندی </h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">

                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <form method="post" action="">
                                        {% csrf_token %}
                                        {% for field in form.visible_fields %}
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">{{ field.label }}</label>
                                                {{ field }}
                                            </div>
                                        {% endfor %}
                                        <button type="submit" class="btn btn-primary">ثبت</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>

    </div>
    <!-- end::main-content -->
{% endblock content %}
<!-- begin::footer -->