accounts/api/urls.py
from django.urls import path

from .views import SendOtpApiView, VerifyApiView

urlpatterns = [
    path("send_otp/", SendOtpApiView.as_view()),
    path("verify/", VerifyApiView.as_view()),
]

accounts/urls.py
from django.urls import include, path

from accounts.api.urls import urlpatterns

from .views import (
    AdminCreateView,
    AdminUserListView,
    LogoutView,
    UserDeleteView,
    UserLoginView,
)

app_name = "accounts"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("admin_list/", AdminUserListView.as_view(), name="admin_list"),
    path("admin_create/", AdminCreateView.as_view(), name="admin_create"),
    path("delete/<int:pk>/", UserDeleteView.as_view(), name="delete"),
    path("api/", include(urlpatterns)),
]

divar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("wantads.urls", namespace="want_ad")),
    path("category/", include("categories.urls")),
    path("panel/", include("config.urls", namespace="config")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += [
        path("silk/", include("silk.urls", namespace="silk")),
        path("__debug__/", include("debug_toolbar.urls")),
    ]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models

from .managers import UserManager

# Create your models here.


class User(AbstractBaseUser, PermissionsMixin):
    phone_number = models.CharField(max_length=11, unique=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = "phone_number"

    objects = UserManager()

    def __str__(self):
        return self.phone_number

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class OtpCode(models.Model):
    phone_number = models.CharField(max_length=11)
    code = models.CharField(max_length=6)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm, ReadOnlyPasswordHashField
from django.core.validators import ValidationError

from .models import User


class CreationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("phone_number",)

    def clean(self):
        clean_data = super(CreationForm, self).clean()
        password, password_confirm = (
            clean_data["password"],
            clean_data["password_confirm"],
        )
        if (password & password_confirm) and (password != password_confirm):
            raise ValidationError("un match password")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class ChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ("phone_number",)


class AuthForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("phone_number", "password")
        labels = {
            "phone_number": "نام کاربری",
            "password": "رمز عبور",
        }
        widgets = {
            "phone_number": forms.TextInput(
                attrs={"placeholder": "", "class": "form-control text-left"}
            ),
            "password": forms.PasswordInput(
                attrs={"placeholder": "رمز عبوز", "class": "form-control text-left"}
            ),
        }


class AdminPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(AdminPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields["old_password"].lable = ""
        self.fields["new_password1"].lable = ""
        self.fields["new_password1"].lable = ""

        for fieldname in ["new_password1", "new_password2", "old_password"]:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].widget.attrs["class"] = "form-control"


class AdminForm(AuthForm):
    password_confirm = forms.CharField(
        label="نایید رمز عبور",
        widget=forms.PasswordInput(
            attrs={"placeholder": "تایید  رمز عبوز", "class": "form-control text-left"}
        ),
    )

    def clean(self):
        clean_data = super(AdminForm, self).clean()
        password, password_confirm = (
            clean_data["password"],
            clean_data["password_confirm"],
        )
        if (password and password_confirm) and (password != password_confirm):
            raise ValidationError("dis match")

accounts/api/views.py
from random import randint

from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.authtoken.models import Token
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response

from ..models import OtpCode
from ..utils import send_otp
from .serializers import PhoneSerializer, VerifySerializer

user = get_user_model()


class SendOtpApiView(GenericAPIView):
    serializer_class = PhoneSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid(raise_exception=True):
            phone_number = serializer.validated_data["phone_number"]
            random_number = randint(111111, 999999)
            otp_code = OtpCode.objects.create(
                phone_number=phone_number, code=random_number
            )
            send_otp(phone_number, random_number)
            contex = {
                "is_done": True,
                "message": "کد برای کاربر ارسال شد",
            }
            return Response(data=contex, status=status.HTTP_200_OK)
        context = {
            "is_done": False,
            "message": serializer.errors,
        }
        return Response(data=context, status=status.HTTP_400_BAD_REQUEST)


class VerifyApiView(GenericAPIView):
    serializer_class = VerifySerializer

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid(raise_exception=True):
            phone_number, code = (
                serializer.validated_data["phone_number"],
                serializer.validated_data["code"],
            )
            otp_obj = OtpCode.objects.filter(phone_number=phone_number,code=code)
            if otp_obj.code == str(code):
                try:
                    user_obj = user.objects.get(phone_number=phone_number)
                    token, create = Token.objects.get_or_create(user_id=user_obj.id)
                    context = {
                        "is_done": True,
                        "message": "کاربر با موفقیت وارد شد",
                        "data": token.key,
                    }
                    return Response(data=context, status=status.HTTP_200_OK)
                except:
                    user_obj = user.objects.create_user(phone_number=phone_number)
                    token = Token.objects.create(user=user_obj)
                    context = {
                        "is_done": True,
                        "message": "کاربر با موفقیت ساخته شد",
                        "data": token.key,
                    }
                    return Response(data=context, status=status.HTTP_200_OK)
            else:
                context = {
                    "is_done": False,
                    "message": "رمز وارد شده درست نمیباشذ",
                }
                return Response(data=context, status=status.HTTP_400_BAD_REQUEST)
        else:
            context = {
                "is_done": False,
                "message": serializer.errors,
            }
            return Response(data=context, status=status.HTTP_502_BAD_GATEWAY)


#
# class LogoutApiView(GenericAPIView):

accounts/views.py
from braces.views import AnonymousRequiredMixin, SuperuserRequiredMixin
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, View

from .forms import AdminForm, AdminPasswordChangeForm, AuthForm

user = get_user_model()


# Create your views here.


class UserLoginView(AnonymousRequiredMixin, FormView):
    form_class = AuthForm
    template_name = "accounts/login.html"
    success_url = reverse_lazy("config:panel")

    def form_valid(self, form):
        clean_data = form.cleaned_data
        user = authenticate(
            self.request,
            phone_number=clean_data["phone_number"],
            password=clean_data["password"],
        )
        if user is not None:
            login(self.request, user)
            messages.success(self.request, "با موفقیت وارد شدید", "success")
        else:
            messages.error(self.request, "خطا در ورود", "danger")
        return super(UserLoginView, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "", "danger")
        return super(UserLoginView, self).form_invalid(form)


class LogoutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        logout(request)
        messages.success(request, "با موفقیت خارج شدید", "success")
        return redirect("accounts:login")


class AdminUserListView(SuperuserRequiredMixin, ListView):
    queryset = user.objects.filter(is_admin=True).exclude(is_superuser=True)
    template_name = "accounts/admin_list.html"
    context_object_name = "admin_list"


class AdminCreateView(SuperuserRequiredMixin, SuccessMessageMixin, FormView):
    form_class = AdminForm
    success_message = "ادمین با موققیت اضافه شد"
    success_url = reverse_lazy("accounts:admin_list")
    template_name = "accounts/admin_create.html"

    def form_valid(self, form):
        clean_data = form.cleaned_data
        user.objects.create_admin(
            phone_number=clean_data["phone_number"], password=clean_data["password"]
        )
        return super(AdminCreateView, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, form.errors, "danger")
        return super(AdminCreateView, self).form_invalid(form)


class UserDeleteView(SuperuserRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user_id = kwargs.get("pk")
        user_obj = get_object_or_404(user, id=user_id)
        user_obj.delete()
        messages.success(request, "", "success")
        return redirect("accounts:admin_list")


class AdminPasswordChangeView(SuccessMessageMixin, PasswordChangeView):
    form_class = AdminPasswordChangeForm
    template_name = ""
    success_url = reverse_lazy("")
    success_message = ""

    def form_invalid(self, form):
        messages.error(self.request, "", "danger")
        return super(AdminPasswordChangeView, self).form_invalid(form)

accounts/templates/accounts/admin_create.html
{% extends 'base1.html' %}
<!-- end::header -->
{% block content %}
    <!-- begin::main-content -->
    <div class="main-content">

        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-success text-center">افزودن کاربر ادمین</h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">

                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <form method="post" action="">
                                        {% csrf_token %}
                                        {% for field in form.visible_fields %}
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">{{ field.label }}</label>
                                                {{ field }}
                                            </div>
                                        {% endfor %}
                                        <button type="submit" class="btn btn-primary">ثبت</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>

    </div>
    <!-- end::main-content -->
{% endblock content %}
<!-- begin::footer -->

accounts/templates/accounts/admin_list.html
{% extends "base1.html" %}
{% block content %}
    <main class="main-content">
        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-center">لیست کاربران ادمین</h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">


                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">کاربران ادمین</h6>
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">شماره تماس</th>
                                        <th scope="col">اخرین ورود</th>
                                        <th scope="col">تنظیمات</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for admin in admin_list %}
                                        <tr>
                                            <th scope="row">{{ forloop.counter }}</th>
                                            <td>{{ admin.phone_number }}</td>
                                            <td> {% if admin.last_login %}
                                                {{ admin.last_login }}
                                            {% else %}
                                                ---
                                            {% endif %}
                                            </td>
                                            <td><a class="btn btn-danger" href="{% url "accounts:delete" admin.pk %}">حذف
                                                ادمین</a></td>
                                        </tr>
                                    {% empty %}
                                        <h1 class="text-center text-danger">ادمینی در سیستم ثبت نشده</h1>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </main>
{% endblock content %}

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>قالب Protable - قالب پنل مدیریت</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'media/image/favicon.png' %}">

    <!-- Plugin styles -->
    <link rel="stylesheet" href="{% static 'vendors/bundle.css' %}" type="text/css">

    <!-- App styles -->
    <link rel="stylesheet" href="{% static 'css/app.css' %}" type="text/css">
</head>
<body class="form-membership">

<!-- begin::preloader-->
<div class="preloader">
    <svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="50px" height="50px" viewbox="0 0 128 128"
         xml:space="preserve">
        <rect x="0" y="0" width="100%" height="100%" fill="#FFFFFF"/>
        <g>
            <path d="M75.4 126.63a11.43 11.43 0 0 1-2.1-22.65 40.9 40.9 0 0 0 30.5-30.6 11.4 11.4 0 1 1 22.27 4.87h.02a63.77 63.77 0 0 1-47.8 48.05v-.02a11.38 11.38 0 0 1-2.93.37z"
                  fill="#000000" fill-opacity="1"/>
        </g>
    </svg>
</div>
<!-- end::preloader -->

<div class="form-wrapper">

    <!-- logo -->
    <div id="logo">
        <img class="logo" src="{% static 'media/image/logo.png' %}" alt="image">
        <img class="logo-dark" src="{% static 'media/image/logo-dark.png' %}" alt="image">
    </div>
    <!-- ./ logo -->

    <h5>ورود</h5>

    <!-- form -->
    <form method="post" action="">
        {% csrf_token %}
        <div class="form-group">
            {{ form.phone_number }}
        </div>
        <div class="form-group">
            {{ form.password }}
        </div>
        <div class="form-group text-left d-sm-flex justify-content-between mb-4">
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" checked id="customCheck1">
                <label class="custom-control-label" for="customCheck1">به خاطر سپاری</label>
            </div>
            <a href="recover-password.html" class="line-height-28">بازنشانی رمز عبور</a>
        </div>
        <button  type="submit" class="btn btn-primary btn-block">ورود</button>
        <hr>
    </form>
    <!-- ./ form -->

</div>

<!-- Plugin scripts -->
<script src="{% static 'vendors/bundle.js' %}"></script>

<!-- App scripts -->
<script src="{% static  'js/app.js' %}"></script>
</body>
</html>