accounts/urls.py
from django.urls import include, path

from accounts.api.urls import urlpatterns

from .views import (
    AdminCreateView,
    AdminUserListView,
    LogoutView,
    UserDeleteView,
    UserLoginView,
)

app_name = "accounts"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("admin_list/", AdminUserListView.as_view(), name="admin_list"),
    path("admin_create/", AdminCreateView.as_view(), name="admin_create"),
    path("delete/<int:pk>/", UserDeleteView.as_view(), name="delete"),
    path("api/", include(urlpatterns)),
]

config/urls.py
from django.urls import path

from .views import PanelView

app_name = "config"
urlpatterns = [
    path("", PanelView.as_view(), name="panel"),
]

divar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("wantads.urls", namespace="want_ad")),
    path("category/", include("categories.urls")),
    path("panel/", include("config.urls", namespace="config")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += [
        path("silk/", include("silk.urls", namespace="silk")),
        path("__debug__/", include("debug_toolbar.urls")),
    ]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for obj in qs %}
    {{ obj.title }}
    {{ obj.created }}
    {{ obj.updated }}
    {{ obj.description }}
{% endfor %}
</body>
</html>

templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>قالب Protable - قالب پنل مدیریت</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'media/image/favicon.png' %}">

    <!-- Plugin styles -->
    <link rel="stylesheet" href="{% static 'vendors/bundle.css' %}" type="text/css">

    <!-- Datepicker -->
    <link rel="stylesheet" href="{% static 'datepicker/daterangepicker.css' %}">

    <!-- Slick -->
    <link rel="stylesheet" href="{% static 'vendors/slick/slick.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/slick/slick-theme.css' %}">

    <!-- Vmap -->
    <link rel="stylesheet" href="{% static 'vendors/vmap/jqvmap.min.css' %}">

    <!-- App styles -->
    <link rel="stylesheet" href="{% static 'css/app.css' %}" type="text/css">
    {% block style %}
    {% endblock style %}
</head>
<body>
<!-- begin::preloader-->

{#<div class="preloader">#}
{#    <svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="50px" height="50px" viewbox="0 0 128 128" xml:space="preserve">#}
{#        <rect x="0" y="0" width="100%" height="100%" fill="#FFFFFF" />#}
{#        <g>#}
{#            <path d="M75.4 126.63a11.43 11.43 0 0 1-2.1-22.65 40.9 40.9 0 0 0 30.5-30.6 11.4 11.4 0 1 1 22.27 4.87h.02a63.77 63.77 0 0 1-47.8 48.05v-.02a11.38 11.38 0 0 1-2.93.37z" fill="#000000" fill-opacity="1" />#}
{#        </g>#}
{#    </svg>#}
{#</div>#}

{% include 'navbar.html' %}
<div id="main">
    {% include 'header.html' %}
    {% block content %}
    {% endblock content %}
    <!-- begin::footer -->
    <footer>
        <div class="container">
            <div>ارائه شده در وب‌سایت <a href="https://www.rtl-theme.com" target="_blank">راست‌چین</a></div>
            <div>
                <nav class="nav">
                    <a href="#" class="nav-link">مجوزها</a>
                    <a href="#" class="nav-link">تغییرات</a>
                    <a href="#" class="nav-link">راهنما</a>
                </nav>
            </div>
        </div>
    </footer>
    <!-- end::footer -->

</div>

<!-- Plugin scripts -->
<script src="{% static 'vendors/bundle.js' %}"></script>

<!-- Chartjs -->
<script src="{% static 'vendors/charts/chartjs/chart.min.js' %}"></script>

<!-- Apex chart -->
<script src="{% static 'vendors/charts/apex/apexcharts.min.js' %}"></script>

<!-- Circle progress -->
<script src="{% static 'vendors/circle-progress/circle-progress.min.js' %}"></script>

<!-- Peity -->
<script src="{% static 'vendors/charts/peity/jquery.peity.min.js' %}"></script>
<script src="{% static 'js/examples/charts/peity.js' %}"></script>

<!-- Datepicker -->
<script src="{% static 'vendors/datepicker/daterangepicker.js' %}"></script>

<!-- Slick -->
<script src="{% static 'vendors/slick/slick.min' %}.js"></script>

<!-- Vamp -->
<script src="{% static 'vendors/vmap/jquery.vmap' %}.min.js"></script>
<script src="{% static 'vendors/vmap/maps/jquery' %}.vmap.usa.js"></script>
<script src="{% static 'js/examples/vmap' %}.js"></script>

<!-- Dashboard scripts -->
<script src="{% static 'js/examples/dashboard.js' %}"></script>
<div class="colors"> <!-- To use theme colors with Javascript -->
    <div class="bg-primary"></div>
    <div class="bg-primary-bright"></div>
    <div class="bg-secondary"></div>
    <div class="bg-secondary-bright"></div>
    <div class="bg-info"></div>
    <div class="bg-info-bright"></div>
    <div class="bg-success"></div>
    <div class="bg-success-bright"></div>
    <div class="bg-danger"></div>
    <div class="bg-danger-bright"></div>
    <div class="bg-warning"></div>
    <div class="bg-warning-bright"></div>
</div>

<!-- App scripts -->
<script src="{% static 'js/app.js' %}"></script>

</body>
</html>

templates/navbar.html
<div class="navigation">

    <!-- begin::logo -->
    <div id="logo">
        <a href="index.html">
            <img class="logo" src="assets/media/image/logo.png" alt="logo">
            <img class="logo-sm" src="assets/media/image/logo-sm.png" alt="small logo">
            <img class="logo-dark" src="assets/media/image/logo-dark.png" alt="dark logo">
        </a>
    </div>
    <!-- end::logo -->

    <!-- begin::navigation header -->
    <header class="navigation-header">
        <figure class="avatar avatar-state-success">
            <img src="assets/media/image/user/man_avatar3.jpg" class="rounded-circle" alt="image">
        </figure>
        <div>
            <h5>جان اسنو</h5>
            <p class="text-muted line-height-20 m-b-25">مدیر</p>
            <ul class="nav">
                <li class="nav-item">
                    <a href="profile.html" class="btn nav-link bg-info-bright" title="پروفایل" data-toggle="tooltip">
                        <i data-feather="user"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="btn nav-link bg-success-bright" title="تنظیمات" data-toggle="tooltip">
                        <i data-feather="settings"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "accounts:logout" %}" class="btn nav-link bg-danger-bright" title="خروج"
                       data-toggle="tooltip">
                        <i data-feather="log-out"></i>
                    </a>
                </li>
            </ul>
        </div>
    </header>
    <!-- end::navigation header -->

    <!-- begin::navigation menu -->
    <div class="navigation-menu-body">
        <ul>
            <li class="navigation-divider">اصلی</li>
            <li class="open">
                <a href="{% url "config:panel" %}">
                    <i class="nav-link-icon" data-feather="bar-chart-2"></i>
                    <span>داشبورد</span>
                </a>
                <ul>
                    <li><a class="active" href="index.html">داشبورد 1</a></li>
                    <li><a href="dashboard-two.html">داشبورد 2</a></li>
                </ul>
            </li>
            <li>
                <a href="{% url "config:panel" %}">
                    <i class="nav-link-icon" data-feather="bar-chart-2"></i>
                    <span>گفتگو</span>
                    <span class="badge badge-danger">2</span>
                </a>
            </li>
            <li>
                <a href="inbox.html">
                    <i class="nav-link-icon" data-feather="mail"></i>
                    <span>ایمیل</span>
                    <span class="badge badge-success">2</span>
                </a>
            </li>
            <li>
                <a href="app-todo.html">
                    <i class="nav-link-icon" data-feather="check-circle"></i>
                    <span>برای انجام</span>
                    <span class="badge badge-warning">2</span>
                </a>
            </li>
            <li>
                <a href="file-manager.html">
                    <i class="nav-link-icon" data-feather="file"></i>
                    <span>مدیریت فایل</span>
                </a>
            </li>
            <li>
                <a href="calendar.html">
                    <i class="nav-link-icon" data-feather="calendar"></i>
                    <span>تقویم</span>
                </a>
            </li>
            <li class="navigation-divider">رابط کاربری</li>
            <li>
                <a href="#">
                    <i class="nav-link-icon" data-feather="monitor"></i>
                    <span>اجزاء</span>
                </a>
                <ul>
                    <li>
                        <a href="#">پایه</a>
                        <ul>
                            <li><a href="alerts.html">هشدار</a></li>
                            <li><a href="accordion.html">باز و بسته شونده</a></li>
                            <li><a href="buttons.html">دکمه ها</a></li>
                            <li><a href="dropdown.html">منوی کشویی</a></li>
                            <li><a href="list-group.html">گروه لیست</a></li>
                            <li><a href="pagination.html">صفحه‌بندی</a></li>
                            <li><a href="typography.html">تایپوگرافی</a></li>
                            <li><a href="media-object.html">رسانه</a></li>
                            <li><a href="progress.html">پیشرفت</a></li>
                            <li><a href="modal.html">مودال</a></li>
                            <li><a href="spinners.html">چرخنده ها</a></li>
                            <li><a href="navs.html">ناوبری ها</a></li>
                            <li><a href="tab.html">تب</a></li>
                            <li><a href="tooltip.html">راهنما (تولتیپ)</a></li>
                            <li><a href="popovers.html">پاپ اور</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">کارت ها</a>
                        <ul>
                            <li><a href="basic-cards.html">کارت های پایه </a></li>
                            <li><a href="image-cards.html">کارت های تصویری </a></li>
                            <li><a href="card-scroll.html">کارت های اسکرول دار </a></li>
                            <li><a href="other-cards.html">سایر </a></li>
                        </ul>
                    </li>
                    <li><a href="avatar.html">آواتار</a></li>
                    <li><a href="icons.html">آیکن‌ها</a></li>
                    <li><a href="colors.html">رنگ ها</a></li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="nav-link-icon" data-feather="globe"></i>
                    <span>پلاگین ها</span>
                </a>
                <ul>
                    <li><a href="sweet-alert.html">هشدار Sweet</a></li>
                    <li><a href="lightbox.html">لایت باکس</a></li>
                    <li><a href="toast.html">توست</a></li>
                    <li><a href="tour.html">تور</a></li>
                    <li><a href="slick-slide.html">اسلاید Slick</a></li>
                    <li><a href="nestable.html">لیست تو در تو</a></li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="nav-link-icon" data-feather="mouse-pointer"></i>
                    <span>فرم ها</span>
                </a>
                <ul>
                    <li><a href="basic-form.html">طرح های فرم</a></li>
                    <li><a href="custom-form.html">فرم های سفارشی</a></li>
                    <li><a href="advanced-form.html">فرم پیشرفته</a></li>
                    <li><a href="form-validation.html">اعتبارسنجی</a></li>
                    <li><a href="form-wizard.html">مرحله ای</a></li>
                    <li><a href="file-upload.html">آپلود فایل</a></li>
                    <li><a href="datepicker.html">انتخاب گر تاریخ</a></li>
                    <li><a href="timepicker.html">انتخاب گر زمان</a></li>
                    <li><a href="colorpicker.html">انتخاب گر رنگ</a></li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="nav-link-icon" data-feather="grid"></i>
                    <span>جدول‌ها</span>
                </a>
                <ul>
                    <li><a href="tables.html">جدول‌های پایه</a></li>
                    <li><a href="data-table.html">جدول اطلاعات</a></li>
                    <li><a href="responsive-table.html">جدول‌های واکنشگرا</a></li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="nav-link-icon" data-feather="pie-chart"></i>
                    <span>نمودار ها</span>
                </a>
                <ul>
                    <li><a href="apexchart.html">Apex</a></li>
                    <li><a href="chartjs.html">Chartjs</a></li>
                    <li><a href="justgage.html">Justgage</a></li>
                    <li><a href="morsis.html">Morsis</a></li>
                    <li><a href="peity.html">Peity</a></li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="nav-link-icon" data-feather="map-pin"></i>
                    <span>نقشه ها</span>
                </a>
                <ul>
                    <li><a href="google-map.html">گوگل</a></li>
                    <li><a href="vector-map.html">وکتور</a></li>
                </ul>
            </li>
            <li class="navigation-divider">متفرقه</li>
            <li>
                <a href="#">
                    <i class="nav-link-icon" data-feather="user"></i>
                    <span>احراز هویت</span>
                </a>
                <ul>
                    <li><a href="login.html">ورود</a></li>
                    <li><a href="register.html">ثبت نام</a></li>
                    <li><a href="recover-password.html">بازیابی رمز عبور</a></li>
                    <li><a href="lock-screen.html">قفل صفحه</a></li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="nav-link-icon" data-feather="copy"></i>
                    <span>صفحات</span>
                </a>
                <ul>
                    <li><a href="profile.html">پروفایل</a></li>
                    <li><a href="timeline.html">خط زمانی</a></li>
                    <li><a href="invoice.html">صورتحساب</a></li>

                    <li><a href="pricing-table.html">جدول قیمت ها</a></li>
                    <li><a href="search-result.html">نتایج جستجو</a></li>
                    <li>
                        <a href="#">صفحات خطا</a>
                        <ul>
                            <li><a href="404.html">404</a></li>
                            <li><a href="404-2.html">404 نسخه 2</a></li>
                            <li><a href="503.html">503</a></li>
                            <li><a href="mean-at-work.html">تعمیرات</a></li>
                        </ul>
                    </li>
                    <li><a href="blank-page.html">صفحه شروع</a></li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="nav-link-icon" data-feather="send"></i>
                    <span>قالب های ایمیل</span>
                </a>
                <ul>
                    <li><a href="email-template-basic.html">پایه</a></li>
                    <li><a href="email-template-alert.html">هشدار</a></li>
                    <li><a href="email-template-billing.html">صورتحساب</a></li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="nav-link-icon" data-feather="menu"></i>
                    <span>سطح منو</span>
                </a>
                <ul>
                    <li>
                        <a href="#">سطح منو</a>
                        <ul>
                            <li>
                                <a href="#">سطح منو </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- end::navigation menu -->

</div>